### ISSUE TITLE
Can not make it to work on android.

### ISSUE THREAD

**Issue by aminmsvi** [arjendeblok/aurelia-cordova-skeleton#1]
Hello.
First thing first, I am new to all this web technologies; Aurelia, WebPack, Cordova, etc.
I appreciate your help with my problem. I wanted to use Aurelia and Cordova together so after search in google I found your skeleton project. It works OK in browser. When I execute `cordova run browser`, it shows _Hello Cordova_. but when I run it using `cordova run android` it only shows _booting...._. I tested it in an android emulator with API 25 and an actual android device. 
Do you know why this happens?

**Comment by arjendeblok** [comment]
Hello Amin,

There is indeed an issue I discovered later on. In the `www `folder the webpack build generates an `index.html` file. The` html-webpack-plugin` generates this file. The problem is that the files `app.css` and `app.js` are referenced by `/app/app.js` and` /app/app.css`. The problem is that the cordova build cannot find these files through these references. 

If you remove the first `/`  for both files in the generated index.html (after the webpack build) and then run `cordova run android` then it works. So it must be` app/app.js` instead of `/app/app.js`

I am still investigating a real solution for this issue.

**Comment by aminmsvi** [comment]
I fixed it. The problem was with path to the app.js inside www/index.html. Changed 
`<script type="text/javascript" src="/app/app.js"></script>` 
to
`<script type="text/javascript" src="app/app.js"></script>`
and it start working in my android emulator. Not sure if its a good fix or not.

**Comment by arjendeblok** [comment]
See my comment above. You are correct. Fix is good.
